[package]
name = "rustycheckers"
version = "0.1.0"
authors = ["Stephen Newman <steve@newman.digital>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mut_static = "5.0.0"
lazy_static = "1.0.2"